name: Deploy Astro to o2switch

on:
  workflow_dispatch:
  push:
    paths:
      - 'apcm-back/**'
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy PayloadCMS (Backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies & build Payload (optional)
        working-directory: ./apcm-back
        run: |
          pnpm install
          pnpm run build

      - name: Deploy backend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./dist/
          server-dir: ${{ secrets.PATH }}


